_pymodule: data
dataset_type: CocoDataset
data_root: 'D:/datasets/object_detection/overhang/new/'

train_dataset:
  _pymodule: data
  type: CocoDataset
  ann_file: ${data_root}/annotations/train.json
  img_prefix: ${data_root}/images/
  pipeline:
    - type: LoadImageFromFile
    - type: LoadAnnotations
      with_bbox: True
    - type: Resize
      scale: [640, 640]
      keep_ratio: True
    - type: RandomFlip
      flip_ratio: 0.5
    - type: Normalize
      mean: [123.675, 116.28, 103.53]
      std: [58.395, 57.12, 57.375]
      to_rgb: True
    - type: Pad
      size_divisor: 32
    - type: DefaultFormatBundle
    - type: Collect
      keys: [img, gt_bboxes, gt_labels]

val_dataset:
  _pymodule: data
  type: CocoDataset
  ann_file: ${data_root}/annotations/val.json
  img_prefix: ${data_root}/images/
  pipeline:
    - type: LoadImageFromFile
    - type: LoadAnnotations
      with_bbox: True
    - type: Resize
      scale: [640, 640]
      keep_ratio: True
    - type: Normalize
      mean: [123.675, 116.28, 103.53]
      std: [58.395, 57.12, 57.375]
      to_rgb: True
    - type: Pad
      size_divisor: 32
    - type: DefaultFormatBundle
    - type: Collect
      keys: [img, gt_bboxes, gt_labels]

train_dataloader:
  _pymodule: data
  dataset: ${train_dataset}
  batch_size: 4
  num_workers: 2
  shuffle: True
  pin_memory: True
  drop_last: True

val_dataloader:
  _pymodule: data
  dataset: ${val_dataset}
  batch_size: 1
  num_workers: 2
  shuffle: False
  pin_memory: True
  drop_last: False